# Course - Introduction to R 

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [ ]:
#### Start solution ####

In [23]:
name <- c("A","W","A","I","S","-","Q","U","A","R","N","I")

nam

[1] "A" "W" "A" "I" "S" "-" "Q" "U" "A" "R" "N" "I"

In [24]:
#2: Concatenate the vector
paste(name, collapse = '')

[1] "AWAIS-QUARNI"

In [29]:
# 3: varaible containing seq from 100 to 120
x <- 100:120
x

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

In [63]:
#4 : create the matrix of 3*3

M <- matrix(seq(1,17, by=2), nrow=3,ncol=3)

M

[,1] [,2] [,3]
[1,] 1     7   13  
[2,] 3     9   15  
[3,] 5    11   17

In [71]:
# 5; Assign name to varaibles

x <- 1:5

names(x) <- c('a','b','c','d','e')

x

a b c d e 
1 2 3 4 5

In [ ]:
#### End solution ####

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [4]:
#### Start solution ####

In [74]:
emp_status <- factor(c('Employed','Unemployed','Self-Employed','Unemployed','Employed','Unemployed','Self-Employed','Self-Employed'))

emp_status


[1] Employed      Unemployed    Self-Employed Unemployed    Employed     
[6] Unemployed    Self-Employed Self-Employed
Levels: Employed Self-Employed Unemployed

emp_status
     Employed Self-Employed    Unemployed 
            2             3             3 

In [76]:
# 2 Display the levels and the factor variable as a table.
table(emp_status)

emp_status
     Employed Self-Employed    Unemployed 
            2             3             3 

In [75]:
# 3 Unclass the elements of the factor variable.
unclass(emp_status)

[1] 1 3 2 3 1 3 2 2
attr(,"levels")
[1] "Employed"      "Self-Employed" "Unemployed"

In [3]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [ ]:
#### Start solution ####

In [9]:
bank_customers <- data.frame(CustomerID = c(1,2,3,4,5), hasAccount=c("Alicia","Nancy","Fernando","Louis","Diane"), totalBalance=c(NA,"10000$",0,"2000$",NA))

bank_customers

CustomerID hasAccount totalBalance
1 1          Alicia     NA          
2 2          Nancy      10000$      
3 3          Fernando   0           
4 4          Louis      2000$       
5 5          Diane      NA

In [10]:
nrow(bank_customers)

[1] 5

In [11]:
ncol(bank_customers)

[1] 3

In [12]:
names(bank_customers)

[1] "CustomerID"   "hasAccount"   "totalBalance"

In [2]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [5]:
#### Start solution ####

In [105]:
p <- 1:100

x <- seq(p)
x

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [13]:
prime_numbers <- function(n) {
if (n >= 2) {
 x = seq(2, n)
 prime_nums = c()
 for (i in seq(2, n)) {
 if (any(x == i)) {
 prime_nums = c(prime_nums, i)
 x = c(x[(x %% i) != 0], i)
 }
 }
 return(prime_nums)
 }
 else 
 {
 stop("Input number should be at least 2.")
 }
 } 
Result = prime_numbers(100)
Result

[1]  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97

In [22]:

var <- 1
count<-0
  while (count < 10){
  if (var==2){
    count<- count+1 
  }  
  if (var >2){  
  f<-TRUE
  n<- as.integer(var/2)
  v<- 2:(n+1)
  for (j in v ) {
    if (var%%j == 0){
      f<- FALSE 
      break
    }
  }
  if (f){
    count<- count+1
    my_num<- var
    }
  }
 var<-var+1   
}
print(my_num)

[1] 29


In [6]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [9]:
#### Start solution ####

In [29]:
mat_1 <- matrix(1:9, nrow=3, ncol=3)

mat_1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [49]:
for(i in seq_len(nrow(mat_1))){
    for(j in seq_len(ncol(mat_1))){
        print(paste("mat_1[",i,",",j,"] = ", mat_1[i,j]))
    }
}

[1] "mat_1[ 1 , 1 ] =  1"
[1] "mat_1[ 1 , 2 ] =  4"
[1] "mat_1[ 1 , 3 ] =  7"
[1] "mat_1[ 2 , 1 ] =  2"
[1] "mat_1[ 2 , 2 ] =  5"
[1] "mat_1[ 2 , 3 ] =  8"
[1] "mat_1[ 3 , 1 ] =  3"
[1] "mat_1[ 3 , 2 ] =  6"
[1] "mat_1[ 3 , 3 ] =  9"


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [9]:
#### Start solution ####

In [70]:
# a <- 36
# b <- 60
gcd <- function(a,b){
    if(a == 0){
        return (b)
    }else if(b == 0){
        return (a)
    }else if(a == b){
        return (a)
    }else if(a > b){
        return (gcd(a-b, b))
    }else{
        return (gcd(a, b-a))
    }
    }
answer <- gcd(18,24)

In [71]:
answer

[1] 6

In [14]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [9]:
#### Start solution ####

In [86]:
allConditionsMeet <- function(a,b){
    if(a == b){
        print(paste(a,b))
        return (TRUE)
    }else{
        print(paste(a,b))
        return (FALSE)
    }
}

allConditionsMeet(3,3)

[1] "3 3"


[1] TRUE

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [9]:
#### Start solution ####

In [93]:
mat_1 <- matrix(1:6, nrow= 2, ncol=3)

mat_2 <- matrix(1:6, nrow=3, ncol=2)

In [94]:
#elment wise multiplication
mat_1 * mat_2  # it generate the error of non-conformable arrays because operate element-by-element, you always need the arrays (or matrices) to be the same size.

ERROR: Error in mat_1 * mat_2: non-conformable arrays


In [95]:
#Matrix wise multiplication

mat_1 %*% mat_2

[,1] [,2]
[1,] 22   49  
[2,] 28   64

In [98]:
#Create a 2x2 matrix my_mat

mat <- matrix(4:7, nrow=2, ncol=2)

mat

[,1] [,2]
[1,] 4    6   
[2,] 5    7

In [99]:
#Write a function to find the determinant of the matrix.

det(mat)  #The determinant is: |A| = ad − bc

[1] -2

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [9]:
#### Start solution ####

In [125]:
curr_time <- Sys.time()
curr_date <- Sys.Date()

curr_time
curr_date

[1] "2021-03-24 18:23:42 PKT"

[1] "2021-03-24"

In [127]:
class(curr_time)

[1] "POSIXct" "POSIXt"

In [134]:
time <- as.POSIXlt(curr_time)
date <- as.POSIXlt(curr_date)
time
date

[1] "2021-03-24 18:23:42 PKT"

[1] "2021-03-24 UTC"

In [142]:
weekdays(curr_date)
months(curr_date)

print(paste("Year ",date$year + 1900))
print(paste("second ",time$sec))
print(paste("Hour ", time$hour))

[1] "Wednesday"

[1] "March"

[1] "Year  2021"
[1] "second  42.5810689926147"
[1] "Hour  18"


In [14]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [9]:
#### Start solution ####

In [228]:
Cur_date <- Sys.time()
Cur_date

[1] "2021-03-24 20:31:36 PKT"

In [229]:
 as.POSIXlt(Sys.time(),  "GMT")

[1] "2021-03-24 15:31:36 GMT"

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [9]:
#### Start solution ####

In [185]:
num <- list(a= 100:150)


In [186]:
lapply(num, mean)
lapply(num, sd)

$a
[1] 125

$a
[1] 14.86607

In [188]:
sapply(num, mean)
sapply(num,sd)

a 
125

a 
14.86607

In [169]:
str(apply)

function (X, MARGIN, FUN, ...)  


In [191]:
number <- matrix(101:150, nrow=10, ncol=5)
number

[,1] [,2] [,3] [,4] [,5]
 [1,] 101  111  121  131  141 
 [2,] 102  112  122  132  142 
 [3,] 103  113  123  133  143 
 [4,] 104  114  124  134  144 
 [5,] 105  115  125  135  145 
 [6,] 106  116  126  136  146 
 [7,] 107  117  127  137  147 
 [8,] 108  118  128  138  148 
 [9,] 109  119  129  139  149 
[10,] 110  120  130  140  150

In [197]:
apply(number, 1, mean)
apply(number, 2, sd)

[1] 121 122 123 124 125 126 127 128 129 130

[1] 3.02765 3.02765 3.02765 3.02765 3.02765

In [219]:
#tapply

number_t <- c(101:150)
number_t

f <- gl(5 , 10)
f
tapply(number_t, f,  mean)
tapply(number_t, f, sd)

[1] 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
[20] 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
[39] 139 140 141 142 143 144 145 146 147 148 149 150

[1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4
[39] 4 4 5 5 5 5 5 5 5 5 5 5
Levels: 1 2 3 4 5

1     2     3     4     5 
105.5 115.5 125.5 135.5 145.5

1       2       3       4       5 
3.02765 3.02765 3.02765 3.02765 3.02765

In [14]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [9]:
#### Start solution ####

In [230]:
x <- matrix(1:16, nrow=4, ncol=4)
x

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [233]:
str(apply)

function (X, MARGIN, FUN, ...)  


In [231]:
# apply loop function use with array and matrix
apply(x,1,mean) # 1 is used for row

[1]  7  8  9 10

In [232]:
# apply loop function use array and matrix 
apply(x, 2, mean) # 2 is for column

[1]  2.5  6.5 10.5 14.5

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [21]:
library(datasets)

In [25]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [9]:
#### Start solution ####

In [234]:
str(split)

function (x, f, drop = FALSE, ...)  


In [248]:
s <- split(Orange, Orange$circumference)

s$'30'
s$'75'


Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

Tree age circumference
17 3    664 75

In [265]:
#Find the average age of the tree when the circumference is 30 and when circumference is 214.

sapply(list(s$'30'$age), mean )

[1] 118

In [269]:
#Find the average age of the tree when the circumference is 30 and when circumference is 214.

sapply(list(s$'214'$age), mean )

[1] 1582

In [14]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!